// --- Party ---
export type PartyId = 'S' | 'M' | 'SD' | 'C' | 'V' | 'KD' | 'L' | 'MP'

export interface PartyInfo {
  id: PartyId
  color: string
  textColor?: string
  bloc: 'left' | 'right' | 'other'
}

export const PARTIES: PartyInfo[] = [
  { id: 'S',  color: '#e81010', bloc: 'left' },
  { id: 'V',  color: '#cc0000', bloc: 'left' },
  { id: 'MP', color: '#83c440', textColor: '#1a3a00', bloc: 'left' },
  { id: 'M',  color: '#1d6ab1', bloc: 'right' },
  { id: 'SD', color: '#cccc00', textColor: '#444400', bloc: 'right' },
  { id: 'KD', color: '#005080', bloc: 'right' },
  { id: 'C',  color: '#009a44', bloc: 'right' },
  { id: 'L',  color: '#0063a5', bloc: 'right' },
]

export function getParty(id: string): PartyInfo | undefined {
  return PARTIES.find(p => p.id === id.toUpperCase())
}

// --- Person ---
export interface Person {
  id: string         // riksdagens ledamot-id
  name: string
  firstName: string
  lastName: string
  party: string
  photoUrl: string   // https://data.riksdagen.se/filarkiv/bilder/ledamot/{id}_max.jpg
}

// --- Debate ---
export interface DebateParticipant {
  person: Person
  role?: string
}

export interface BlocSummary {
  parties: string[]
  summary: string
  keyArg: string
}

export interface Debate {
  id: string
  title: string
  topic: string
  topicEmoji: string
  date: string
  venue: string
  videoUrl?: string
  dokId?: string
  participants: DebateParticipant[]
  // Generated by AI
  ingress?: string
  leftBloc?: BlocSummary
  rightBloc?: BlocSummary
  aiLoading?: boolean
  aiError?: string
}

// --- Vote ---
export interface PartyVote {
  party: string
  ja: number
  nej: number
  avstar: number
  franvarande: number
}

export interface Vote {
  id: string
  title: string
  topicEmoji: string
  date: string
  totalJa: number
  totalNej: number
  totalAvstar: number
  totalFranvarande: number
  partyVotes: PartyVote[]
  dokId?: string
  outcome: 'ja' | 'nej'
  // Generated by AI
  humanTitle?: string
  jaMeaning?: string
  nejMeaning?: string
  consequence?: string
  aiLoading?: boolean
  aiError?: string
}

// --- Filters ---
export interface ActiveFilters {
  parties: string[]
  regions: string[]
}

export const SWEDISH_REGIONS = [
  'Stockholms län', 'Västra Götaland', 'Skåne', 'Uppsala',
  'Södermanland', 'Östergötland', 'Jönköping', 'Kronoberg',
  'Kalmar', 'Gotland', 'Blekinge', 'Halland', 'Värmland',
  'Örebro', 'Västmanland', 'Dalarna', 'Gävleborg',
  'Västernorrland', 'Jämtland', 'Västerbotten', 'Norrbotten',
]
